package duke.exception;

public enum DukeExceptionCause {
    INVALIDCOMMAND,
    EVENTTASKNAMEEMPTY,
    DEADLINETASKNAMEEMPTY,
    TODOTASKNAMEEMPTY,
    EMPTYTASKINDEX,
    TASKINDEXOUTOFRANGE,
    INVALIDTASKINDEX,
    FILECREATIONFAIL,
    FOLDERCREATIONFAIL
}
