/**
 * Focuses on handling exceptions generated by Sora's functions
 */
public class SoraExceptionHandler {
    // Allows SoraExceptionHandler to provide UI outputs to the user
    private SoraUI soraUI;

    public SoraExceptionHandler(SoraUI soraUIObj) {
        this.soraUI = soraUIObj;
    }

    public void handleInvalidCommandException(InvalidCommandException e) {
        String errorMessage = e.getMessage();

        switch (errorMessage) {
        case InvalidCommandException.NO_SUCH_COMMAND_MSG:
            soraUI.printCommandNotUnderstood();
            break;
        case InvalidCommandException.TODO_NO_DESCRIPTION:
            soraUI.printTodoMissingDescription();
            break;
        }
    }
}
