package command;

import duke.Storage;
import duke.TaskList;
import duke.Ui;
import task.Deadlines;
import task.Events;
import task.Task;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class AddCommand extends Command{
    private final String taskType;

    private final String description;

    private final String time;

    /**
     * The constructor of AddCommand
     * @param taskType A string indicates the task type
     * @param description The description of the task
     * @param time the deadline of deadlines or duration of events
     */
    public AddCommand(String taskType, String description, String time) {
        this.taskType = taskType;
        this.description = description;
        this.time = time;
    }

    /**
     *
     * A method to execute AddCommand
     *
     * @param taskList duke's task list
     * @param ui duke's ui
     * @param storage duke's storage
     * @return A string generated by ui
     */
    @Override
    public String execute(TaskList taskList, Ui ui, Storage storage) {

        if(taskType.contains("deadlines")) {
            Deadlines deadline = new Deadlines(description, time);
            taskList.add(deadline);
        }
        else if(taskType.contains("events")) {
            Events event = new Events(description, time);
            taskList.add(event);
        }
        else {
            Task task = new Task(description);
            taskList.add(task);
        }
        return ui.generateResponse(String.format("%s\nNow you have %d tasks in you list.\n", taskList.getTask(taskList.size()), taskList.size()));
    }
}
