package command;

import duke.Storage;
import duke.TaskList;
import duke.Ui;
import duke.exception.DukeException;
import task.Deadlines;
import task.Events;
import task.Task;

public abstract class Command {
    /**
     * A method to check if the command is an ExitCommand
     *
     * @return A boolean value indicates whether the command is an ExitCommand
     */
    public boolean isExit() {
        return false;
    }

    /**
     * A method to execute the command
     * @param taskList duke's task list
     * @param ui duke's ui
     * @param storage duke's storage
     * @return A string generated by ui
     * @throws DukeException
     */
    public abstract String execute(TaskList taskList, Ui ui, Storage storage) throws DukeException;
}

