package command;

import duke.Storage;
import duke.TaskList;
import duke.Ui;
import task.Deadlines;
import task.Task;

public class DeleteCommand extends Command {
    private final int taskIndex;

    /**
     * The constructor of DeleteCommand
     * @param taskIndex the index of the task that will be deleted
     */
    public DeleteCommand(int taskIndex) {
        this.taskIndex = taskIndex;
    }

    /**
     * A method to execute DeleteCommand
     * @param taskList duke's task list
     * @param ui duke's ui
     * @param storage duke's storage
     * @return A string generated by ui
     */
    @Override
    public String execute(TaskList taskList, Ui ui, Storage storage) {
        taskList.delete(this.taskIndex);
        return ui.generateResponse("Noted. I've removed this task:\n" + taskList.getTask(taskIndex) + "\n" +
                    "Now you have " + (taskList.amountOfTasks() - 1) +" tasks in the list.\n");
    }
}
