package command;

import duke.Storage;
import duke.TaskList;
import duke.Ui;
import duke.exception.DukeException;

public class ExitCommand extends Command {

    /**
     * A constructor of ExitCommand
     */
    public ExitCommand() {
        ;
    }

    /**
     * A method to execute ExitCommand
     * @param taskList duke's task list
     * @param ui duke's ui
     * @param storage duke's storage
     * @return A string generated by ui
     * @throws DukeException
     */
    @Override
    public String execute(TaskList taskList, Ui ui, Storage storage) throws DukeException {
        storage.saveTaskList(taskList);
        return ui.generateResponse("Bye. Hope to see you again soon!\n");
    }
}
