package command;

import duke.Storage;
import duke.TaskList;
import duke.Ui;

public class ListCommand extends Command {
    /**
     * A constructor of ListCommand
     */
    public ListCommand() {
        ;
    }

    /**
     * A method to execute ListCommand
     * @param taskList duke's task list
     * @param ui duke's ui
     * @param storage duke's storage
     * @return A string generated by ui
     */
    @Override
    public String execute(TaskList taskList, Ui ui, Storage storage) {
        return ui.generateResponse(taskList.toString());
    }
}
